exp:
  expname: luna16_50
  expdir: ./logs/Lineformer/
    #datadir: ./data/luna16_50_256.pickle
  train_datadir: ./data/luna16/
  eval_datadir: ./data/luna16/
    #datadir: ./data/luna16_50.pickle
    #network:
    #  net_type: Lineformer
    #  net_type: mlp
    #  num_layers: 4
    #  hidden_dim: 32
    #  skips: [2]
    #  out_dim: 1
    #  last_activation: sigmoid
    #  bound: 0.3
    #  line_size: 2
    #  dim_head: 4
    #  heads: 8
    #  num_blocks: 1
#network:
#  #net_type: mlp
#  #num_layers: 4
#  #hidden_dim: 128
#  #skips: [4]
#  #out_dim: 1
#  #last_activation: relu
#  #bound: 0.3
#  net_type: mlp
#  num_layers: 4
#  hidden_dim: 128
#  skips: [4]
#  out_dim: 1
#  last_activation: relu
#  bound: 0.3
#    #encoder:
#    #  encoding: tensorf
#    #  num_levels: 256
network:
  #net_type: mlp
  #num_layers: 4
  #hidden_dim: 128
  #skips: [4]
  #out_dim: 1
  #last_activation: relu
  #bound: 0.3
  net_type: mlp
  num_layers: 4
  hidden_dim: 128
  skips: [4]
  out_dim: 1
  last_activation: relu
  bound: 0.3
    #encoder:
    #  encoding: tensorf
    #  num_levels: 256
encoder:
  encoding: hashgrid
  #encoding: None
  #encoding: tensorf
  #encoding: sphere_harmonics
  #encoding: tiledgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19
render:
  n_samples: 256    
  n_fine: 0         
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600  # batchsize of points
train:
  epoch: 200
  n_batch: 1
  n_rays: 1024
  n_samples: 256
    #n_rays: 512
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 1500
  resume: False
  window_size: [8, 8]
  window_num: 16
log:
  i_eval: 10  # Epoch for evaluation
  i_save: 100  # Epoch for saving
