exp:
  expname: luna16_50
  expdir: ./logs/Lineformer/
    #datadir: ./data/luna16_50_256.pickle
    #train_datadir: ./data/luna16_17_5_train.pickle
    #eval_datadir: ./data/luna16_17_5_eval.pickle
    #datadir: ./data/luna16_50.pickle
    #datadir: ./data/luna16_17.pickle
    #datadir: ./data/chest_50.pickle
  datadir: ./data/luna16/data.pickle
#network:
  #net_type: Lineformer
  #num_layers: 4
  #hidden_dim: 32
  #skips: [2]
  #out_dim: 1
  #last_activation: sigmoid
  #bound: 0.3
  #line_size: 2
  #dim_head: 4
  #heads: 8
  #num_blocks: 1
network:
  net_type: mlp
  num_layers: 4
  hidden_dim: 128
  skips: [4]
  out_dim: 1
  last_activation: relu
  bound: 0.3
    #encoder:
    #  encoding: tensorf
    #  num_levels: 256
encoder:
  encoding: hashgrid
  #encoding: None
  #encoding: tensorf
  #encoding: sphere_harmonics
  #encoding: tiledgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19
    #encoder:
    #  encoding: sphere_harmonics
    #  input_dim: 3
    #  degree: 6
  #encoding: None
  #encoding: tensorf
  #encoding: sphere_harmonics
  #encoding: tiledgrid
render:
  n_samples: 1024
  n_fine: 0         
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600  # batchsize of points
train:
  epoch: 1000
  n_batch: 1
  n_rays: 2048
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 1500
  resume: False
  window_size: [8, 8]
  window_num: 16
log:
  i_eval: 50  # Epoch for evaluation
  i_save: 100  # Epoch for saving
