exp:
  expname: leg_50
  expdir: ./logs/tensorf/
  datadir: ./data/leg_50.pickle
network:
  net_type: mlp
  num_layers: 4
  hidden_dim: 64
  skips: [2]
  out_dim: 1
  last_activation: relu
  bound: 0.3
encoder:
  encoding: tensorf
  num_levels: 256
render:
  n_samples: 192
  n_fine: 192
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600
train:
  epoch: 3000
  n_batch: 1
  n_rays: 1024
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 1500
  resume: False
log:
  i_eval: 250  # Epoch for evaluation
  i_save: 500  # Epoch for saving
